version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - CAPA
  - CGOA
  - CNPA
  - CNPE
  - fieldnamedocscheck
  - Kubestronaut
  - LFCS
  - OTCA
ignoreWords: []
import: []
