version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - apiextensions
  - apiregistration
  - apiserver
  - apiserverinternal
  - CAPA
  - CGOA
  - CNPA
  - CNPE
  - Kubestronaut
  - LFCS
  - mlajkim
  - OTCA
  - OTCA - CAPA - CGOA - CNPA - CNPE - Kubestronaut - LFCS - mlajkim - OTCA -
    udemy
  - poweroff
ignoreWords: []
import: []
